FROM node:22-alpine AS build
WORKDIR /app/apps/base-web
COPY apps/base-web/package.json apps/base-web/package-lock.json ./
RUN npm ci
COPY apps/base-web ./
RUN npm run build

FROM nginx:alpine AS run
COPY apps/base-web/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/apps/base-web/dist /usr/share/nginx/html
EXPOSE 80
