apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/chcooai/base-api
    newTag: 5e31f279a8455651424cac35883d4b89e082eb28 # api
  - name: ghcr.io/chcooai/base-web
    newTag: 5e31f279a8455651424cac35883d4b89e082eb28 # web
