apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/chcooai/base-api
    newTag: 40ba539de72cf1ce4ad4d1b89cec68888b62992b # api
  - name: ghcr.io/chcooai/base-web
    newTag: 40ba539de72cf1ce4ad4d1b89cec68888b62992b # web
