apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/chcooai/base-api
    newTag: 67556f880ed292712411ba3dc94f8fc114e2bed3 # api
  - name: ghcr.io/chcooai/base-web
    newTag: 67556f880ed292712411ba3dc94f8fc114e2bed3 # web
